var nconf = require('nconf');
nconf.set('GCLOUD_PROJECT', 'ae-maps-prod');
nconf.set('DOMAIN', 'http://www.tumunicipioemprende.es');
nconf.set('googleCallback', 'http://www.tumunicipioemprende.es/api/user/google/callback');
nconf.set('NODE_PORT', 8080);
nconf.set('DS_PROJECT', 'ae-maps-prod');
nconf.set('DB_USER', 'root');
nconf.set('DB_PASS', 'map.rulez!');
nconf.set('DB_NAME', 'db');
nconf.set('DB_SOCKET_PATH', '/cloudsql/' + process.env.INSTANCE_CONNECTION_NAME);
